backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "project"
    label: "Project"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Tools Used", name: "tools", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string", required: false }
